import {createRequire} from 'node:module'
import {mkdir} from 'node:fs/promises'
const require=createRequire(import.meta.url)
const {chromium}=require(require.resolve('playwright',{paths:[process.cwd(),process.cwd()+'/.superpowers/browser-tools']}))
const browser=await chromium.launch({headless:true,executablePath:process.env.LANES_CHROMIUM_PATH})
await mkdir('.superpowers/browser-results',{recursive:true})
const errors=[]
try {
 for(const size of [{name:'desktop',width:1440,height:900},{name:'mobile',width:390,height:844}]){
  const page=await browser.newPage({viewport:size})
  page.on('pageerror',error=>errors.push(error.message))
  await page.goto('http://127.0.0.1:3299/tests/browser/index.html')
  await page.getByRole('button',{name:'LN-4 options',exact:true}).click()
  await page.getByRole('menuitem',{name:'Open card',exact:true}).focus()
  await page.keyboard.press('ArrowDown')
  if(!await page.getByRole('menuitem',{name:'Assign to me',exact:true}).evaluate(el=>el===document.activeElement))throw new Error('Menu focus navigation failed')
  await page.keyboard.press('Escape')
  await page.keyboard.press('j')
  await page.locator('[data-card-id]').first().evaluate((el,size)=>el.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:size.width-2,clientY:size.height-2})),size)
  await page.getByRole('menuitem',{name:'Move to',exact:true}).focus()
  await page.keyboard.press('Enter')
  await page.getByRole('menu',{name:'Actions submenu'}).waitFor()
  if(await page.getByText('Custom fields',{exact:true}).count())throw new Error('Menu Enter opened card panel')
  for(const menu of await page.getByRole('menu').all()){
   const box=await menu.boundingBox()
   if(!box||box.x<0||box.y<0||box.x+box.width>size.width+1||box.y+box.height>size.height+1)throw new Error('Menu outside viewport '+JSON.stringify({size,box,styles:await menu.evaluate(el=>({inline:el.getAttribute("style"),position:getComputedStyle(el).position,html:el.outerHTML.slice(0,200)})),viewport:await page.evaluate(()=>({width:innerWidth,height:innerHeight,visualWidth:visualViewport?.width}))}))
  }
  await page.keyboard.press('Escape')
  await page.getByLabel('Filter cards',{exact:true}).fill('Design')
  await page.getByLabel('Select all visible cards').check()
  await page.getByText('1 selected',{exact:true}).waitFor()
  await page.getByRole('button',{name:'Clear selection',exact:true}).click()
  await page.getByRole('button',{name:'table',exact:true}).click()
  await page.getByRole('table',{name:'Cards table'}).waitFor()
  await page.getByRole('button',{name:'board',exact:true}).click()
  await page.getByRole('button',{name:'LN-4 options',exact:true}).click()
  await page.getByRole('menuitem',{name:'Open card',exact:true}).click()
  await page.getByText('Custom fields',{exact:true}).waitFor()
  await page.getByLabel('Budget',{exact:true}).fill('125')
  await page.getByRole('button',{name:'Save fields',exact:true}).click()
  await page.getByRole('button',{name:'Close',exact:true}).click()
  await page.screenshot({path:`.superpowers/browser-results/${size.name}-board.png`,fullPage:true})
  await page.goto('http://127.0.0.1:3299/tests/browser/index.html?surface=settings')
  await page.getByLabel('Board name',{exact:true}).fill('Customized board')
  await page.getByRole('button',{name:'Save changes'}).click()
  await page.getByRole('status').filter({hasText:'Changes saved.'}).waitFor()
  await page.goto('http://127.0.0.1:3299/tests/browser/index.html?surface=fields')
  await page.getByRole('button',{name:'Add field',exact:true}).click()
  await page.getByLabel('Name',{exact:true}).fill('Customer reference')
  await page.getByRole('button',{name:'Save field',exact:true}).click()
  await page.getByRole('button',{name:'Add field',exact:true}).waitFor()
  await page.close()
  console.log(`${size.name}: menu keyboard, selection, table, card fields, settings and field editor passed`)
 }
 if(errors.length)throw new Error(errors.join('\n'))
}finally{await browser.close()}
