import { beforeAll, afterAll, expect, it } from 'vitest'
import { PGlite } from '@electric-sql/pglite'
import { PgDialect } from 'drizzle-orm/pg-core'
import { bulkStatement } from '@/lib/lanes/bulk-sql'
import type { BulkOperation } from '@/lib/lanes/bulk-validation'
const uuid=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`
const tenant=uuid(1),board=uuid(2),other=uuid(3),todo=uuid(4),done=uuid(5),a=uuid(6),b=uuid(7),foreign=uuid(8)
let pg:PGlite
const execute=async(ids:string[],op:BulkOperation)=>{const v=await pg.query<{v:number}>('select coalesce(settings->>\'_lanesBulkVersion\',\'0\')::integer as v from projects where id=$1',[board]);const q=new PgDialect().sqlToQuery(bulkStatement(board,tenant,'u',ids,op,v.rows[0].v));return pg.query<{updated:number}>(q.sql,q.params)}
beforeAll(async()=>{pg=new PGlite();await pg.exec(`create type card_priority as enum('urgent','high','medium','low');create table projects(id uuid primary key,tenant_id uuid,settings jsonb default '{}',deleted_at timestamptz,updated_at timestamptz);create table project_lists(id uuid primary key,project_id uuid,is_done_list boolean,deleted_at timestamptz);create table tenant_memberships(tenant_id uuid,user_id text,deleted_at timestamptz);create table project_cards(id uuid primary key,project_id uuid,list_id uuid,position integer,priority card_priority default 'medium',due_date timestamptz,completed_at timestamptz,completed_by_id text,updated_at timestamptz,archived_at timestamptz,deleted_at timestamptz);create table project_card_members(id uuid,card_id uuid,user_id text,created_at timestamptz);create table project_activity(id uuid,project_id uuid,tenant_id uuid,user_id text,card_id uuid,type text,description text,created_at timestamptz);insert into projects(id,tenant_id)values('${board}','${tenant}'),('${other}','${uuid(10)}');insert into project_lists(id,project_id,is_done_list)values('${todo}','${board}',false),('${done}','${board}',true);insert into tenant_memberships values('${tenant}','u',null);insert into project_cards(id,project_id,list_id,position)values('${a}','${board}','${todo}',0),('${b}','${board}','${todo}',1),('${foreign}','${other}','${todo}',2);`)})
afterAll(async()=>{await pg?.close()})
it('rejects mixed boards and invalid destinations without writes or activity',async()=>{expect((await execute([a,foreign],{type:'priority',value:'urgent'})).rows[0].updated).toBe(0);expect((await execute([a,b],{type:'move',listId:uuid(99)})).rows[0].updated).toBe(0);expect((await execute([a,b],{type:'assignee-add',userId:'foreign'})).rows[0].updated).toBe(0);expect((await pg.query('select * from project_activity')).rows).toHaveLength(0);expect((await pg.query('select priority from project_cards where id=$1',[a])).rows[0].priority).toBe('medium')})
it('updates all valid cards and completion semantics atomically',async()=>{expect((await execute([a,b],{type:'move',listId:done})).rows[0].updated).toBe(2);const completed=await pg.query('select completed_at from project_cards where project_id=$1',[board]);expect(completed.rows.every(c=>c.completed_at)).toBe(true);expect((await execute([a,b],{type:'move',listId:todo})).rows[0].updated).toBe(2);expect((await pg.query('select completed_at from project_cards where project_id=$1',[board])).rows.every(c=>c.completed_at===null)).toBe(true)})
it('adds/removes assignees idempotently and updates dates and priorities',async()=>{await execute([a,b],{type:'assignee-add',userId:'u'});await execute([a,b],{type:'assignee-add',userId:'u'});expect((await pg.query('select * from project_card_members')).rows).toHaveLength(2);await execute([a,b],{type:'assignee-remove',userId:'u'});expect((await pg.query('select * from project_card_members')).rows).toHaveLength(0);await execute([a,b],{type:'due-date',value:'2026-10-01'});await execute([a,b],{type:'priority',value:'high'});const c=await pg.query('select priority,due_date from project_cards where project_id=$1',[board]);expect(c.rows.every(c=>c.priority==='high'&&c.due_date)).toBe(true);await execute([a,b],{type:'due-date',value:null});expect((await pg.query('select due_date from project_cards where project_id=$1',[board])).rows.every(c=>c.due_date===null)).toBe(true)})
it('rejects archived or deleted cards without partial changes',async()=>{await execute([a],{type:'archive'});const before=await pg.query('select count(*)::int n from project_activity');expect((await execute([a,b],{type:'priority',value:'urgent'})).rows[0].updated).toBe(0);expect((await pg.query('select count(*)::int n from project_activity')).rows).toEqual(before.rows)})
