import { expect, it } from 'vitest'
import { fieldDefinitionSchema, validateFieldValues, validateChoiceChange } from '@/lib/lanes/field-validation'
const field=(type:string,extra={})=>({id:'id',key:'field',name:'Field',type,options:[{value:'a',label:'A'},{value:'b',label:'B'}],required:false,showOnCard:false,position:0,...extra})
it.each([['text','hello'],['number',12.5],['select','a'],['multi_select',['a','b']],['date','2026-09-30'],['checkbox',false],['url','https://axxes.club'],['user','user']])('validates %s values',(type,value)=>{expect(validateFieldValues([field(type)],{field:value},['user'])).toEqual({field:value})})
it.each([['number',Infinity],['number','12'],['date','2026-02-30'],['date','yesterday'],['url','javascript:alert(1)'],['user','foreign'],['select','c'],['multi_select',['a','a']],['checkbox','yes'],['text',12]])('rejects invalid %s',(type,value)=>{expect(()=>validateFieldValues([field(type)],{field:value},['user'])).toThrow()})
it('rejects reserved keys and unknown values',()=>{for(const key of ['seq','__proto__','constructor','prototype','_internal'])expect(fieldDefinitionSchema.safeParse({name:'Field',key,type:'text'}).success).toBe(false);expect(()=>validateFieldValues([field('text')],{seq:1},[])).toThrow()})
it('requires nonblank values but accepts false and zero',()=>{expect(()=>validateFieldValues([field('text',{required:true})],{},[])).toThrow();expect(()=>validateFieldValues([field('text',{required:true})],{field:' '},[])).toThrow();expect(validateFieldValues([field('checkbox',{required:true})],{field:false},[])).toEqual({field:false});expect(validateFieldValues([field('number',{required:true})],{field:0},[])).toEqual({field:0});expect(validateFieldValues([field('text')],{field:''},[])).toEqual({field:null})})
it('rejects removal of choices referenced by active cards',()=>{expect(()=>validateChoiceChange(field('select'),[{value:'b',label:'B'}],[{field:'a'}])).toThrow();expect(()=>validateChoiceChange(field('select'),[{value:'b',label:'B'}],[{field:'b'}])).not.toThrow()})
it('rejects duplicated option values and immutable identity/type patches',()=>{expect(fieldDefinitionSchema.safeParse({key:'severity',name:'Severity',type:'select',options:[{value:'a',label:'A'},{value:'a',label:'Again'}]}).success).toBe(false)})
