'use client'
import { useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { bulkUpdateCards } from '@/lib/lanes/bulk-actions'
import type { BulkOperation } from '@/lib/lanes/bulk-validation'
import type { BoardT } from '@/lib/lanes/types'
export function BulkToolbar({board,ids,can,onClear}:{board:BoardT;ids:string[];can:Record<string,boolean>;onClear:()=>void}){
 const router=useRouter();const [type,setType]=useState<BulkOperation['type']>('move'),[value,setValue]=useState(''),[error,setError]=useState(''),[confirm,setConfirm]=useState(false),[pending,start]=useTransition()
 const types=[['move','Move','card.move'],['priority','Priority','card.priority'],['assignee-add','Add assignee','card.assign'],['assignee-remove','Remove assignee','card.assign'],['due-date','Due date','card.update'],['archive','Archive','card.delete']] as const
 const allowed=types.filter(([, ,permission])=>can[permission]===true)
 const selected=allowed.some(([t])=>t===type)?type:allowed[0]?.[0]
 if(!ids.length)return null
 return <form className="mb-3 flex flex-wrap items-center gap-2 rounded-lg border border-accent/30 bg-accent-soft p-3" onSubmit={(e)=>{e.preventDefault();if(!selected||pending)return;if(selected==='archive'&&!confirm){setConfirm(true);return}const operation:BulkOperation=selected==='move'?{type:selected,listId:value}:selected==='priority'?{type:selected,value:value as 'high'}:selected==='assignee-add'||selected==='assignee-remove'?{type:selected,userId:value}:selected==='due-date'?{type:selected,value:value||null}:{type:'archive'};setError('');start(async()=>{try{await bulkUpdateCards(board.id,ids,operation);onClear();setConfirm(false);router.refresh()}catch(e){setError(e instanceof Error?e.message:'Could not update cards.')}})}}>
 <span className="mr-2 text-sm font-medium">{ids.length} selected</span>{allowed.length>0&&<><select aria-label="Bulk action" className="input h-9 w-auto" disabled={pending} value={selected} onChange={(e)=>{setType(e.target.value as BulkOperation['type']);setValue('');setConfirm(false)}}>{allowed.map(([type,label])=><option key={type} value={type}>{label}</option>)}</select>
 {selected==='move'?<select aria-label="Destination column" required className="input h-9 w-auto" disabled={pending} value={value} onChange={e=>setValue(e.target.value)}><option value="">Choose column</option>{board.lists.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select>:selected==='priority'?<select aria-label="Bulk priority" required className="input h-9 w-auto" disabled={pending} value={value} onChange={e=>setValue(e.target.value)}><option value="">Choose priority</option>{['urgent','high','medium','low'].map(p=><option key={p}>{p}</option>)}</select>:selected==='assignee-add'||selected==='assignee-remove'?<select aria-label="Bulk assignee" required className="input h-9 w-auto" disabled={pending} value={value} onChange={e=>setValue(e.target.value)}><option value="">Choose person</option>{board.people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>:selected==='due-date'?<label className="text-xs">Blank clears dates<input aria-label="Bulk due date" type="date" className="input ml-2 h-9 w-auto" disabled={pending} value={value} onChange={e=>setValue(e.target.value)}/></label>:null}
 <button className="btn-primary btn-sm" disabled={pending||ids.length>100}>{pending?'Updating…':confirm?'Confirm archive':'Apply'}</button></>}<button type="button" className="btn-ghost" disabled={pending} onClick={onClear}>Clear selection</button>{confirm&&<p className="w-full text-xs">Archive all {ids.length} selected cards? Click Confirm archive to continue.</p>}{ids.length>100&&<p role="alert" className="w-full text-sm text-danger">Select at most 100 cards per operation.</p>}{error&&<p role="alert" className="w-full text-sm text-danger">{error}</p>}</form>
}
