'use client'
import { useState, useTransition } from 'react'
import { saveCardFields } from '@/lib/lanes/field-actions'
import { fieldDisplay, type FieldDefinition } from '@/lib/lanes/field-validation'
import type { PersonT } from '@/lib/lanes/types'
export function CardFields({cardId,fields,values,people,canEdit,onSaved}:{cardId:string;fields:FieldDefinition[];values:Record<string,unknown>;people:PersonT[];canEdit:boolean;onSaved:()=>Promise<void>}){
 const [draft,setDraft]=useState(values),[error,setError]=useState(''),[pending,start]=useTransition()
 const set=(key:string,value:unknown)=>setDraft({...draft,[key]:value})
 if(!fields.length)return null
 return <form className="space-y-3" onSubmit={(e)=>{e.preventDefault();setError('');start(async()=>{try{await saveCardFields(cardId,Object.fromEntries(fields.map(f=>[f.key,draft[f.key]??null])));await onSaved()}catch(e){setError(e instanceof Error?e.message:'Could not save fields.')}})}}><h3 className="text-xs font-medium uppercase tracking-wider text-muted">Custom fields</h3><fieldset disabled={!canEdit||pending} className="grid gap-4 sm:grid-cols-2">{fields.map(f=>{const value=draft[f.key];return <label key={f.id} className="block text-sm"><span>{f.name}{f.required&&<span className="ml-1 text-danger" aria-label="required">*</span>}</span>
 {!canEdit?<span className="mt-1 block text-muted">{fieldDisplay(f,value,people)}</span>:f.type==='checkbox'?<input className="ml-3" type="checkbox" checked={value===true} onChange={e=>set(f.key,e.target.checked)}/>:f.type==='select'||f.type==='user'?<select className="input mt-1 w-full" value={typeof value==='string'?value:''} required={f.required} onChange={e=>set(f.key,e.target.value||null)}><option value="">Not set</option>{f.type==='user'?people.map(p=><option key={p.id} value={p.id}>{p.name}</option>):f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='multi_select'?<select multiple className="input mt-1 w-full" value={Array.isArray(value)?value as string[]:[]} required={f.required} onChange={e=>set(f.key,Array.from(e.target.selectedOptions,o=>o.value))}>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input className="input mt-1 w-full" type={f.type==='number'?'number':f.type==='date'?'date':f.type==='url'?'url':'text'} step={f.type==='number'?'any':undefined} required={f.required} value={typeof value==='string'||typeof value==='number'?value:''} onChange={e=>set(f.key,f.type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value||null)}/>}
 {value==null&&f.required&&<span className="mt-1 block text-xs text-warning">Needs a value</span>}</label>})}</fieldset>{error&&<p role="alert" className="text-sm text-danger">{error}</p>}{canEdit&&<button className="btn-primary btn-sm" disabled={pending}>{pending?'Saving…':'Save fields'}</button>}</form>
}
