'use client'
import { useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { FIELD_TYPES, type FieldDefinition, type FieldDefinitionInput, type FieldType } from '@/lib/lanes/field-validation'
import { createField, updateField, deleteField, reorderFields } from '@/lib/lanes/field-actions'
import { fieldKey } from '@/lib/lanes/prefix'
import { ConfirmDialog } from './confirm-dialog'
export function FieldsPanel({ boardId, fields, canManage }: {boardId:string;fields:FieldDefinition[];canManage:boolean}) {
 const router=useRouter();const [pending,start]=useTransition();const [error,setError]=useState('');const [editing,setEditing]=useState<FieldDefinition|null>(null);const [creating,setCreating]=useState(false);const [removing,setRemoving]=useState<FieldDefinition|null>(null)
 const run=(action:()=>Promise<void>)=>start(async()=>{setError('');try{await action();setCreating(false);setEditing(null);setRemoving(null);router.refresh()}catch(e){setError(e instanceof Error?e.message:'Could not save fields.')}})
 return <section className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Custom fields</h2><p className="mt-1 text-sm text-muted">Track the details your team needs on every card.</p></div>{canManage&&<button type="button" className="btn-primary" disabled={pending} onClick={()=>{setEditing(null);setCreating(true)}}>Add field</button>}</div>
 {error&&<p role="alert" className="rounded-lg bg-danger-soft p-3 text-sm text-danger">{error}</p>}
 {(creating||editing)&&<FieldForm key={editing?.id??'new'} field={editing} pending={pending} onCancel={()=>{setCreating(false);setEditing(null)}} onSave={(input)=>run(()=>editing?updateField(boardId,editing.id,{name:input.name,options:input.options,required:input.required,showOnCard:input.showOnCard}):createField(boardId,input))}/>}
 {!fields.length&&!creating&&<div className="card p-8 text-center text-sm text-muted">Add a field for severity, budget, approval, or any detail your team tracks.</div>}
 <div className="space-y-2">{fields.map((f,i)=><div key={f.id} className="card flex flex-wrap items-center gap-3 p-4"><div className="min-w-0 flex-1"><p className="font-medium">{f.name}</p><p className="text-xs text-muted">{f.type.replaceAll('_',' ')}{f.required?' · Required':''}{f.showOnCard?' · Shown on cards':''}</p></div>{canManage&&<><button type="button" className="btn-ghost" aria-label={`Move ${f.name} up`} disabled={pending||i===0} onClick={()=>{const ids=fields.map(f=>f.id);[ids[i-1],ids[i]]=[ids[i],ids[i-1]];run(()=>reorderFields(boardId,ids))}}>↑</button><button type="button" className="btn-ghost" aria-label={`Move ${f.name} down`} disabled={pending||i===fields.length-1} onClick={()=>{const ids=fields.map(f=>f.id);[ids[i],ids[i+1]]=[ids[i+1],ids[i]];run(()=>reorderFields(boardId,ids))}}>↓</button><button type="button" className="btn-ghost" disabled={pending} onClick={()=>{setCreating(false);setEditing(f)}}>Edit</button><button type="button" className="btn-ghost text-danger" disabled={pending} onClick={()=>setRemoving(f)}>Delete</button></>}</div>)}</div>
 <ConfirmDialog open={!!removing} title={`Delete ${removing?.name??'field'}?`} description="The field will disappear from cards. Existing values are retained, and its key cannot be reused." pending={pending} onClose={()=>setRemoving(null)} onConfirm={()=>removing&&run(()=>deleteField(boardId,removing.id))}/></section>
}
function FieldForm({field,pending,onSave,onCancel}:{field:FieldDefinition|null;pending:boolean;onSave:(input:FieldDefinitionInput)=>void;onCancel:()=>void}){
 const [name,setName]=useState(field?.name??''),[key,setKey]=useState(field?.key??''),[type,setType]=useState<FieldType>((field?.type as FieldType)??'text'),[options,setOptions]=useState(field?.options??[]),[required,setRequired]=useState(field?.required??false),[show,setShow]=useState(field?.showOnCard??false)
 return <form className="card space-y-4 p-5" onSubmit={(e)=>{e.preventDefault();onSave({name,key:key||fieldKey(name),type,options:['select','multi_select'].includes(type)?options:[],required,showOnCard:show})}}><fieldset disabled={pending} className="space-y-4">
 <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Name<input className="input mt-1 w-full" required maxLength={100} value={name} onChange={(e)=>setName(e.target.value)}/></label><label className="text-sm">Field key<input className="input mt-1 w-full" disabled={!!field} placeholder={fieldKey(name)||'severity'} value={key} onChange={(e)=>setKey(e.target.value)}/></label></div>
 <label className="block text-sm">Type<select className="input mt-1 w-full" value={type} disabled={!!field} onChange={(e)=>setType(e.target.value as FieldType)}>{FIELD_TYPES.map(t=><option key={t} value={t}>{t.replaceAll('_',' ')}</option>)}</select></label>
 {['select','multi_select'].includes(type)&&<div className="space-y-2"><p className="text-sm font-medium">Choices</p>{options.map((o,i)=><div key={i} className="flex gap-2"><input className="input flex-1" required aria-label={`Choice ${i+1} label`} placeholder="Label" value={o.label} onChange={(e)=>setOptions(options.map((v,j)=>j===i?{...v,label:e.target.value}:v))}/><input className="input flex-1" required aria-label={`Choice ${i+1} value`} placeholder="Stable value" value={o.value} onChange={(e)=>setOptions(options.map((v,j)=>j===i?{...v,value:e.target.value}:v))}/><button type="button" className="btn-ghost" aria-label={`Remove choice ${i+1}`} onClick={()=>setOptions(options.filter((_,j)=>j!==i))}>×</button></div>)}<button type="button" className="btn-ghost" onClick={()=>setOptions([...options,{label:'',value:''}])}>Add choice</button></div>}
 <div className="flex flex-wrap gap-5"><label className="flex gap-2 text-sm"><input type="checkbox" checked={required} onChange={(e)=>setRequired(e.target.checked)}/>Required</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={show} onChange={(e)=>setShow(e.target.checked)}/>Show on cards</label></div><p className="text-xs text-muted">Keys and types stay fixed after creation.</p><div className="flex gap-2"><button className="btn-primary">{pending?'Saving…':'Save field'}</button><button type="button" className="btn-ghost" onClick={onCancel}>Cancel</button></div></fieldset></form>
}
