'use client'
import { useState,useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { saveView,updateView,deleteView } from '@/lib/lanes/view-actions'
import type { SavedView,SavedViewState,ViewMode } from '@/lib/lanes/view-validation'
export function SavedViews({boardId,views,state,view,me,canShare,onApply}:{boardId:string;views:SavedView[];state:SavedViewState;view:ViewMode;me:string;canShare:boolean;onApply:(view:SavedView)=>void}){
 const [current,setCurrent]=useState(''),[editing,setEditing]=useState(false),[name,setName]=useState(''),[shared,setShared]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(false),[pending,start]=useTransition();const router=useRouter();const selected=views.find(v=>v.id===current);const editable=selected&&(selected.isShared?canShare:selected.userId===me)
 const run=(action:()=>Promise<void>)=>start(async()=>{setError('');try{await action();setEditing(false);setConfirm(false);router.refresh()}catch(e){setError(e instanceof Error?e.message:'Could not save view.')}})
 return <div className="mb-3 space-y-2"><div className="flex flex-wrap items-center gap-2"><select aria-label="Saved view" className="input h-9 w-auto" disabled={pending} value={current} onChange={(e)=>{setCurrent(e.target.value);setConfirm(false);const v=views.find(v=>v.id===e.target.value);if(v)onApply(v)}}><option value="">Saved views</option>{views.map(v=><option key={v.id} value={v.id}>{v.name}{v.isShared?' · Shared':' · Personal'}</option>)}</select><button type="button" className="btn-ghost text-xs" disabled={pending} onClick={()=>{setCurrent('');setName('');setShared(false);setEditing(true)}}>Save current view</button>{editable&&<><button type="button" className="btn-ghost text-xs" disabled={pending} onClick={()=>{setName(selected.name);setShared(selected.isShared);setEditing(true)}}>Update view</button><button type="button" className="btn-ghost text-xs text-danger" disabled={pending} onClick={()=>{if(!confirm){setConfirm(true);return}run(async()=>{await deleteView(boardId,selected.id);setCurrent('')})}}>{confirm?'Confirm delete':'Delete view'}</button></>}</div>
 {editing&&<form className="card flex flex-wrap items-center gap-3 p-3" onSubmit={(e)=>{e.preventDefault();const input={name,isShared:shared,state,view};run(()=>current?updateView(boardId,current,input):saveView(boardId,input))}}><label className="text-sm">View name<input className="input ml-2 h-9" required maxLength={100} value={name} disabled={pending} onChange={(e)=>setName(e.target.value)}/></label>{canShare&&<label className="flex gap-2 text-sm"><input type="checkbox" checked={shared} disabled={pending} onChange={(e)=>setShared(e.target.checked)}/>Share with board</label>}<button className="btn-primary btn-sm" disabled={pending}>{pending?'Saving…':'Save'}</button><button type="button" className="btn-ghost" disabled={pending} onClick={()=>setEditing(false)}>Cancel</button></form>}{error&&<p role="alert" className="text-sm text-danger">{error}</p>}</div>
}
